-- Treescape.nvim plugin highlights
-- Support for LazyVim and popular Neovim plugins

local M = {}

local function set_hl(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

function M.setup(c, config)
	local transparent = config.transparent
	local bg = transparent and "NONE" or c.bg

	-----------------------------------------------------------------------------
	-- Telescope
	-----------------------------------------------------------------------------
	set_hl("TelescopeNormal", { fg = c.fg, bg = c.pmenu })
	set_hl("TelescopeBorder", { fg = c.border, bg = c.pmenu })
	set_hl("TelescopeTitle", { fg = c.green_bright, bg = c.pmenu, bold = true })
	set_hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg_highlight })
	set_hl("TelescopePromptBorder", { fg = c.border, bg = c.bg_highlight })
	set_hl("TelescopePromptTitle", { fg = c.green_bright, bg = c.bg_highlight, bold = true })
	set_hl("TelescopePromptPrefix", { fg = c.green_bright })
	set_hl("TelescopePromptCounter", { fg = c.comment })
	set_hl("TelescopeResultsNormal", { fg = c.fg, bg = c.pmenu })
	set_hl("TelescopeResultsBorder", { fg = c.border, bg = c.pmenu })
	set_hl("TelescopeResultsTitle", { fg = c.green_bright, bg = c.pmenu })
	set_hl("TelescopePreviewNormal", { fg = c.fg, bg = c.bg_dark })
	set_hl("TelescopePreviewBorder", { fg = c.border, bg = c.bg_dark })
	set_hl("TelescopePreviewTitle", { fg = c.green_bright, bg = c.bg_dark })
	set_hl("TelescopeSelection", { fg = c.green_bright, bg = c.bg_visual })
	set_hl("TelescopeSelectionCaret", { fg = c.green_bright })
	set_hl("TelescopeMultiSelection", { fg = c.mist })
	set_hl("TelescopeMultiIcon", { fg = c.mist })
	set_hl("TelescopeMatching", { fg = c.sunflower, bold = true })
	set_hl("TelescopePreviewLine", { bg = c.bg_visual })
	set_hl("TelescopePreviewMatch", { fg = c.sunflower, bold = true })

	-----------------------------------------------------------------------------
	-- Neo-tree
	-----------------------------------------------------------------------------
	set_hl("NeoTreeNormal", { fg = c.fg, bg = c.bg_dark })
	set_hl("NeoTreeNormalNC", { fg = c.fg, bg = c.bg_dark })
	set_hl("NeoTreeVertSplit", { fg = c.border, bg = c.bg_dark })
	set_hl("NeoTreeWinSeparator", { fg = c.border, bg = c.bg_dark })
	set_hl("NeoTreeEndOfBuffer", { fg = c.bg_dark, bg = c.bg_dark })
	set_hl("NeoTreeRootName", { fg = c.green_bright, bold = true })
	set_hl("NeoTreeGitAdded", { fg = c.git_add })
	set_hl("NeoTreeGitDeleted", { fg = c.git_delete })
	set_hl("NeoTreeGitModified", { fg = c.git_change })
	set_hl("NeoTreeGitConflict", { fg = c.berry, bold = true })
	set_hl("NeoTreeGitUntracked", { fg = c.purple })
	set_hl("NeoTreeGitIgnored", { fg = c.comment })
	set_hl("NeoTreeGitStaged", { fg = c.green })
	set_hl("NeoTreeIndentMarker", { fg = c.border })
	set_hl("NeoTreeExpander", { fg = c.comment })
	set_hl("NeoTreeFileIcon", { fg = c.fg })
	set_hl("NeoTreeFileName", { fg = c.fg })
	set_hl("NeoTreeFileNameOpened", { fg = c.green_bright })
	set_hl("NeoTreeSymbolicLinkTarget", { fg = c.mist })
	set_hl("NeoTreeFilterTerm", { fg = c.sunflower, bold = true })
	set_hl("NeoTreeDimText", { fg = c.comment })
	set_hl("NeoTreeTitleBar", { fg = c.green_bright, bg = c.bg_highlight, bold = true })
	set_hl("NeoTreeFloatBorder", { fg = c.border })
	set_hl("NeoTreeFloatTitle", { fg = c.green_bright, bold = true })
	set_hl("NeoTreeCursorLine", { bg = c.bg_visual })

	-----------------------------------------------------------------------------
	-- nvim-tree
	-----------------------------------------------------------------------------
	set_hl("NvimTreeNormal", { fg = c.fg, bg = c.bg_dark })
	set_hl("NvimTreeNormalNC", { fg = c.fg, bg = c.bg_dark })
	set_hl("NvimTreeRootFolder", { fg = c.green_bright, bold = true })
	set_hl("NvimTreeFolderIcon", { fg = c.green })
	set_hl("NvimTreeFolderName", { fg = c.green })
	set_hl("NvimTreeOpenedFolderName", { fg = c.green_bright })
	set_hl("NvimTreeEmptyFolderName", { fg = c.comment })
	set_hl("NvimTreeSymlink", { fg = c.mist })
	set_hl("NvimTreeExecFile", { fg = c.green_bright, bold = true })
	set_hl("NvimTreeSpecialFile", { fg = c.purple })
	set_hl("NvimTreeImageFile", { fg = c.purple })
	set_hl("NvimTreeIndentMarker", { fg = c.border })
	set_hl("NvimTreeGitDirty", { fg = c.git_change })
	set_hl("NvimTreeGitStaged", { fg = c.git_add })
	set_hl("NvimTreeGitMerge", { fg = c.orange })
	set_hl("NvimTreeGitRenamed", { fg = c.purple })
	set_hl("NvimTreeGitNew", { fg = c.git_add })
	set_hl("NvimTreeGitDeleted", { fg = c.git_delete })
	set_hl("NvimTreeGitIgnored", { fg = c.comment })
	set_hl("NvimTreeWindowPicker", { fg = c.bg, bg = c.green, bold = true })
	set_hl("NvimTreeCursorLine", { bg = c.bg_visual })

	-----------------------------------------------------------------------------
	-- Bufferline
	-----------------------------------------------------------------------------
	set_hl("BufferLineFill", { bg = c.bg_dark })
	set_hl("BufferLineBackground", { fg = c.comment, bg = c.bg_dark })
	set_hl("BufferLineBuffer", { fg = c.comment, bg = c.bg_dark })
	set_hl("BufferLineBufferVisible", { fg = c.fg, bg = c.bg_dark })
	set_hl("BufferLineBufferSelected", { fg = c.green_bright, bg = bg, bold = true })
	set_hl("BufferLineTab", { fg = c.comment, bg = c.bg_dark })
	set_hl("BufferLineTabSelected", { fg = c.green_bright, bg = bg, bold = true })
	set_hl("BufferLineTabSeparator", { fg = c.bg_dark, bg = c.bg_dark })
	set_hl("BufferLineTabSeparatorSelected", { fg = c.bg_dark, bg = bg })
	set_hl("BufferLineTabClose", { fg = c.berry, bg = c.bg_dark })
	set_hl("BufferLineIndicatorSelected", { fg = c.green_bright, bg = bg })
	set_hl("BufferLineIndicatorVisible", { fg = c.comment, bg = c.bg_dark })
	set_hl("BufferLineSeparator", { fg = c.bg_dark, bg = c.bg_dark })
	set_hl("BufferLineSeparatorVisible", { fg = c.bg_dark, bg = c.bg_dark })
	set_hl("BufferLineSeparatorSelected", { fg = c.bg_dark, bg = bg })
	set_hl("BufferLineCloseButton", { fg = c.comment, bg = c.bg_dark })
	set_hl("BufferLineCloseButtonVisible", { fg = c.fg, bg = c.bg_dark })
	set_hl("BufferLineCloseButtonSelected", { fg = c.berry, bg = bg })
	set_hl("BufferLineModified", { fg = c.orange, bg = c.bg_dark })
	set_hl("BufferLineModifiedVisible", { fg = c.orange, bg = c.bg_dark })
	set_hl("BufferLineModifiedSelected", { fg = c.orange, bg = bg })
	set_hl("BufferLineDuplicate", { fg = c.comment, bg = c.bg_dark, italic = true })
	set_hl("BufferLineDuplicateSelected", { fg = c.fg, bg = bg, italic = true })
	set_hl("BufferLineDuplicateVisible", { fg = c.comment, bg = c.bg_dark, italic = true })
	set_hl("BufferLineError", { fg = c.error, bg = c.bg_dark })
	set_hl("BufferLineErrorDiagnostic", { fg = c.error, bg = c.bg_dark })
	set_hl("BufferLineWarning", { fg = c.warning, bg = c.bg_dark })
	set_hl("BufferLineWarningDiagnostic", { fg = c.warning, bg = c.bg_dark })
	set_hl("BufferLineInfo", { fg = c.info, bg = c.bg_dark })
	set_hl("BufferLineInfoDiagnostic", { fg = c.info, bg = c.bg_dark })
	set_hl("BufferLineHint", { fg = c.hint, bg = c.bg_dark })
	set_hl("BufferLineHintDiagnostic", { fg = c.hint, bg = c.bg_dark })
	set_hl("BufferLineNumbers", { fg = c.comment, bg = c.bg_dark })
	set_hl("BufferLineNumbersVisible", { fg = c.fg, bg = c.bg_dark })
	set_hl("BufferLineNumbersSelected", { fg = c.green_bright, bg = bg })
	set_hl("BufferLinePick", { fg = c.berry, bg = c.bg_dark, bold = true })
	set_hl("BufferLinePickVisible", { fg = c.berry, bg = c.bg_dark, bold = true })
	set_hl("BufferLinePickSelected", { fg = c.berry, bg = bg, bold = true })
	set_hl("BufferLineOffsetSeparator", { fg = c.border, bg = c.bg_dark })

	-----------------------------------------------------------------------------
	-- Lualine (via theme table, but also set highlights)
	-----------------------------------------------------------------------------
	set_hl("lualine_a_normal", { fg = c.bg, bg = c.green, bold = true })
	set_hl("lualine_b_normal", { fg = c.fg, bg = c.bg_highlight })
	set_hl("lualine_c_normal", { fg = c.fg, bg = c.bg_dark })
	set_hl("lualine_a_insert", { fg = c.bg, bg = c.bark, bold = true })
	set_hl("lualine_a_visual", { fg = c.bg, bg = c.purple, bold = true })
	set_hl("lualine_a_replace", { fg = c.bg, bg = c.berry, bold = true })
	set_hl("lualine_a_command", { fg = c.bg, bg = c.sunflower, bold = true })
	set_hl("lualine_a_inactive", { fg = c.comment, bg = c.bg_dark })

	-----------------------------------------------------------------------------
	-- Which-key
	-----------------------------------------------------------------------------
	set_hl("WhichKey", { fg = c.green_bright })
	set_hl("WhichKeyGroup", { fg = c.stream })
	set_hl("WhichKeyDesc", { fg = c.fg })
	set_hl("WhichKeySeperator", { fg = c.comment })
	set_hl("WhichKeySeparator", { fg = c.comment })
	set_hl("WhichKeyFloat", { bg = c.pmenu })
	set_hl("WhichKeyBorder", { fg = c.border, bg = c.pmenu })
	set_hl("WhichKeyValue", { fg = c.comment })

	-----------------------------------------------------------------------------
	-- Indent Blankline
	-----------------------------------------------------------------------------
	set_hl("IndentBlanklineChar", { fg = c.bg_highlight, nocombine = true })
	set_hl("IndentBlanklineContextChar", { fg = c.green_dim, nocombine = true })
	set_hl("IndentBlanklineContextStart", { sp = c.green_dim, underline = true })
	set_hl("IndentBlanklineSpaceChar", { fg = c.bg_highlight, nocombine = true })
	set_hl("IndentBlanklineSpaceCharBlankline", { fg = c.bg_highlight, nocombine = true })
	-- ibl (v3)
	set_hl("IblIndent", { fg = c.bg_highlight, nocombine = true })
	set_hl("IblWhitespace", { fg = c.bg_highlight, nocombine = true })
	set_hl("IblScope", { fg = c.green_dim, nocombine = true })

	-----------------------------------------------------------------------------
	-- Gitsigns
	-----------------------------------------------------------------------------
	set_hl("GitSignsAdd", { fg = c.git_add })
	set_hl("GitSignsChange", { fg = c.git_change })
	set_hl("GitSignsDelete", { fg = c.git_delete })
	set_hl("GitSignsAddNr", { fg = c.git_add })
	set_hl("GitSignsChangeNr", { fg = c.git_change })
	set_hl("GitSignsDeleteNr", { fg = c.git_delete })
	set_hl("GitSignsAddLn", { bg = c.diff_add })
	set_hl("GitSignsChangeLn", { bg = c.diff_change })
	set_hl("GitSignsDeleteLn", { bg = c.diff_delete })
	set_hl("GitSignsCurrentLineBlame", { fg = c.comment, italic = true })
	set_hl("GitSignsAddPreview", { fg = c.git_add })
	set_hl("GitSignsDeletePreview", { fg = c.git_delete })

	-----------------------------------------------------------------------------
	-- nvim-cmp
	-----------------------------------------------------------------------------
	set_hl("CmpItemAbbr", { fg = c.fg })
	set_hl("CmpItemAbbrDeprecated", { fg = c.comment, strikethrough = true })
	set_hl("CmpItemAbbrMatch", { fg = c.green_bright, bold = true })
	set_hl("CmpItemAbbrMatchFuzzy", { fg = c.green_bright, bold = true })
	set_hl("CmpItemMenu", { fg = c.comment })
	set_hl("CmpItemKind", { fg = c.purple })
	set_hl("CmpItemKindText", { fg = c.fg })
	set_hl("CmpItemKindMethod", { fg = c.green_bright })
	set_hl("CmpItemKindFunction", { fg = c.green_bright })
	set_hl("CmpItemKindConstructor", { fg = c.stream })
	set_hl("CmpItemKindField", { fg = c.fg })
	set_hl("CmpItemKindVariable", { fg = c.fg })
	set_hl("CmpItemKindClass", { fg = c.stream })
	set_hl("CmpItemKindInterface", { fg = c.stream })
	set_hl("CmpItemKindModule", { fg = c.stream })
	set_hl("CmpItemKindProperty", { fg = c.fg })
	set_hl("CmpItemKindUnit", { fg = c.sunflower })
	set_hl("CmpItemKindValue", { fg = c.sunflower })
	set_hl("CmpItemKindEnum", { fg = c.stream })
	set_hl("CmpItemKindKeyword", { fg = c.green })
	set_hl("CmpItemKindSnippet", { fg = c.purple })
	set_hl("CmpItemKindColor", { fg = c.purple })
	set_hl("CmpItemKindFile", { fg = c.bark })
	set_hl("CmpItemKindReference", { fg = c.mist })
	set_hl("CmpItemKindFolder", { fg = c.green })
	set_hl("CmpItemKindEnumMember", { fg = c.fg })
	set_hl("CmpItemKindConstant", { fg = c.bark })
	set_hl("CmpItemKindStruct", { fg = c.stream })
	set_hl("CmpItemKindEvent", { fg = c.orange })
	set_hl("CmpItemKindOperator", { fg = c.fg_dark })
	set_hl("CmpItemKindTypeParameter", { fg = c.stream })
	set_hl("CmpItemKindCopilot", { fg = c.mist })

	-----------------------------------------------------------------------------
	-- blink.cmp
	-----------------------------------------------------------------------------
	set_hl("BlinkCmpMenu", { fg = c.fg, bg = c.pmenu })
	set_hl("BlinkCmpMenuBorder", { fg = c.border, bg = c.pmenu })
	set_hl("BlinkCmpMenuSelection", { bg = c.pmenu_sel })
	set_hl("BlinkCmpLabel", { fg = c.fg })
	set_hl("BlinkCmpLabelMatch", { fg = c.green_bright, bold = true })
	set_hl("BlinkCmpLabelDetail", { fg = c.comment })
	set_hl("BlinkCmpLabelDescription", { fg = c.comment })
	set_hl("BlinkCmpLabelDeprecated", { fg = c.comment, strikethrough = true })
	set_hl("BlinkCmpKind", { fg = c.purple })
	set_hl("BlinkCmpKindText", { fg = c.fg })
	set_hl("BlinkCmpKindMethod", { fg = c.green_bright })
	set_hl("BlinkCmpKindFunction", { fg = c.green_bright })
	set_hl("BlinkCmpKindConstructor", { fg = c.stream })
	set_hl("BlinkCmpKindField", { fg = c.fg })
	set_hl("BlinkCmpKindVariable", { fg = c.fg })
	set_hl("BlinkCmpKindClass", { fg = c.stream })
	set_hl("BlinkCmpKindInterface", { fg = c.stream })
	set_hl("BlinkCmpKindModule", { fg = c.stream })
	set_hl("BlinkCmpKindProperty", { fg = c.fg })
	set_hl("BlinkCmpKindUnit", { fg = c.sunflower })
	set_hl("BlinkCmpKindValue", { fg = c.sunflower })
	set_hl("BlinkCmpKindEnum", { fg = c.stream })
	set_hl("BlinkCmpKindKeyword", { fg = c.green })
	set_hl("BlinkCmpKindSnippet", { fg = c.purple })
	set_hl("BlinkCmpKindColor", { fg = c.purple })
	set_hl("BlinkCmpKindFile", { fg = c.bark })
	set_hl("BlinkCmpKindReference", { fg = c.mist })
	set_hl("BlinkCmpKindFolder", { fg = c.green })
	set_hl("BlinkCmpKindEnumMember", { fg = c.bark })
	set_hl("BlinkCmpKindConstant", { fg = c.bark })
	set_hl("BlinkCmpKindStruct", { fg = c.stream })
	set_hl("BlinkCmpKindEvent", { fg = c.orange })
	set_hl("BlinkCmpKindOperator", { fg = c.fg_dark })
	set_hl("BlinkCmpKindTypeParameter", { fg = c.stream })
	set_hl("BlinkCmpDoc", { fg = c.fg, bg = c.pmenu })
	set_hl("BlinkCmpDocBorder", { fg = c.border, bg = c.pmenu })
	set_hl("BlinkCmpDocCursorLine", { bg = c.bg_visual })
	set_hl("BlinkCmpSignatureHelp", { fg = c.fg, bg = c.pmenu })
	set_hl("BlinkCmpSignatureHelpBorder", { fg = c.border, bg = c.pmenu })
	set_hl("BlinkCmpSignatureHelpActiveParameter", { fg = c.green_bright, bold = true })
	set_hl("BlinkCmpGhostText", { fg = c.comment })

	-----------------------------------------------------------------------------
	-- nvim-notify
	-----------------------------------------------------------------------------
	set_hl("NotifyERRORBorder", { fg = c.error })
	set_hl("NotifyWARNBorder", { fg = c.warning })
	set_hl("NotifyINFOBorder", { fg = c.info })
	set_hl("NotifyDEBUGBorder", { fg = c.comment })
	set_hl("NotifyTRACEBorder", { fg = c.purple })
	set_hl("NotifyERRORIcon", { fg = c.error })
	set_hl("NotifyWARNIcon", { fg = c.warning })
	set_hl("NotifyINFOIcon", { fg = c.info })
	set_hl("NotifyDEBUGIcon", { fg = c.comment })
	set_hl("NotifyTRACEIcon", { fg = c.purple })
	set_hl("NotifyERRORTitle", { fg = c.error })
	set_hl("NotifyWARNTitle", { fg = c.warning })
	set_hl("NotifyINFOTitle", { fg = c.info })
	set_hl("NotifyDEBUGTitle", { fg = c.comment })
	set_hl("NotifyTRACETitle", { fg = c.purple })
	set_hl("NotifyERRORBody", { fg = c.fg })
	set_hl("NotifyWARNBody", { fg = c.fg })
	set_hl("NotifyINFOBody", { fg = c.fg })
	set_hl("NotifyDEBUGBody", { fg = c.fg })
	set_hl("NotifyTRACEBody", { fg = c.fg })

	-----------------------------------------------------------------------------
	-- noice.nvim
	-----------------------------------------------------------------------------
	set_hl("NoiceCmdline", { fg = c.fg })
	set_hl("NoiceCmdlineIcon", { fg = c.green_bright })
	set_hl("NoiceCmdlineIconSearch", { fg = c.sunflower })
	set_hl("NoiceCmdlinePopup", { fg = c.fg, bg = c.pmenu })
	set_hl("NoiceCmdlinePopupBorder", { fg = c.border })
	set_hl("NoiceCmdlinePopupBorderSearch", { fg = c.sunflower })
	set_hl("NoiceConfirm", { fg = c.fg, bg = c.pmenu })
	set_hl("NoiceConfirmBorder", { fg = c.border })
	set_hl("NoiceMini", { fg = c.fg, bg = c.bg_highlight })
	set_hl("NoicePopup", { fg = c.fg, bg = c.pmenu })
	set_hl("NoicePopupBorder", { fg = c.border })
	set_hl("NoicePopupmenu", { fg = c.fg, bg = c.pmenu })
	set_hl("NoicePopupmenuBorder", { fg = c.border })
	set_hl("NoicePopupmenuMatch", { fg = c.green_bright, bold = true })
	set_hl("NoicePopupmenuSelected", { bg = c.pmenu_sel })
	set_hl("NoiceScrollbar", { fg = c.comment })
	set_hl("NoiceScrollbarThumb", { fg = c.green_dim })
	set_hl("NoiceSplit", { fg = c.fg, bg = bg })
	set_hl("NoiceSplitBorder", { fg = c.border })
	set_hl("NoiceVirtualText", { fg = c.comment })

	-----------------------------------------------------------------------------
	-- Lazy.nvim
	-----------------------------------------------------------------------------
	set_hl("LazyNormal", { fg = c.fg, bg = c.pmenu })
	set_hl("LazyButton", { fg = c.fg, bg = c.bg_highlight })
	set_hl("LazyButtonActive", { fg = c.bg, bg = c.green })
	set_hl("LazyComment", { fg = c.comment })
	set_hl("LazyCommit", { fg = c.comment })
	set_hl("LazyCommitIssue", { fg = c.bark })
	set_hl("LazyCommitScope", { fg = c.comment, italic = true })
	set_hl("LazyCommitType", { fg = c.stream })
	set_hl("LazyDimmed", { fg = c.comment })
	set_hl("LazyDir", { fg = c.green })
	set_hl("LazyH1", { fg = c.bg, bg = c.green, bold = true })
	set_hl("LazyH2", { fg = c.green_bright, bold = true })
	set_hl("LazyLocal", { fg = c.orange })
	set_hl("LazyNoCond", { fg = c.berry })
	set_hl("LazyPluginName", { fg = c.fg, bold = true })
	set_hl("LazyProgressDone", { fg = c.green_bright })
	set_hl("LazyProgressTodo", { fg = c.comment })
	set_hl("LazyProp", { fg = c.comment })
	set_hl("LazyReasonCmd", { fg = c.green })
	set_hl("LazyReasonEvent", { fg = c.orange })
	set_hl("LazyReasonFt", { fg = c.mist })
	set_hl("LazyReasonImport", { fg = c.fg })
	set_hl("LazyReasonKeys", { fg = c.purple })
	set_hl("LazyReasonPlugin", { fg = c.stream })
	set_hl("LazyReasonRuntime", { fg = c.bark })
	set_hl("LazyReasonSource", { fg = c.bark })
	set_hl("LazyReasonStart", { fg = c.sunflower })
	set_hl("LazySpecial", { fg = c.purple })
	set_hl("LazyTaskError", { fg = c.error })
	set_hl("LazyTaskOutput", { fg = c.fg })
	set_hl("LazyUrl", { fg = c.stream, underline = true })
	set_hl("LazyValue", { fg = c.bark })

	-----------------------------------------------------------------------------
	-- Mason
	-----------------------------------------------------------------------------
	set_hl("MasonNormal", { fg = c.fg, bg = c.pmenu })
	set_hl("MasonHeader", { fg = c.bg, bg = c.green, bold = true })
	set_hl("MasonHeaderSecondary", { fg = c.bg, bg = c.bark, bold = true })
	set_hl("MasonHighlight", { fg = c.green_bright })
	set_hl("MasonHighlightBlock", { fg = c.bg, bg = c.green })
	set_hl("MasonHighlightBlockBold", { fg = c.bg, bg = c.green, bold = true })
	set_hl("MasonHighlightSecondary", { fg = c.bark })
	set_hl("MasonHighlightBlockSecondary", { fg = c.bg, bg = c.bark })
	set_hl("MasonHighlightBlockBoldSecondary", { fg = c.bg, bg = c.bark, bold = true })
	set_hl("MasonMuted", { fg = c.comment })
	set_hl("MasonMutedBlock", { fg = c.comment, bg = c.bg_highlight })
	set_hl("MasonMutedBlockBold", { fg = c.comment, bg = c.bg_highlight, bold = true })
	set_hl("MasonError", { fg = c.error })
	set_hl("MasonWarning", { fg = c.warning })
	set_hl("MasonHeading", { fg = c.green_bright, bold = true })

	-----------------------------------------------------------------------------
	-- flash.nvim
	-----------------------------------------------------------------------------
	set_hl("FlashBackdrop", { fg = c.comment })
	set_hl("FlashMatch", { fg = c.fg, bg = c.bg_visual })
	set_hl("FlashCurrent", { fg = c.green_bright, bg = c.bg_visual, bold = true })
	set_hl("FlashLabel", { fg = c.bg, bg = c.sunflower, bold = true })
	set_hl("FlashPrompt", { fg = c.fg, bg = c.pmenu })
	set_hl("FlashPromptIcon", { fg = c.green_bright })
	set_hl("FlashCursor", { bg = c.bg_visual })

	-----------------------------------------------------------------------------
	-- mini.nvim
	-----------------------------------------------------------------------------
	-- mini.indentscope
	set_hl("MiniIndentscopeSymbol", { fg = c.green_dim })
	set_hl("MiniIndentscopeSymbolOff", { fg = c.bg_highlight })
	-- mini.statusline
	set_hl("MiniStatuslineDevinfo", { fg = c.fg, bg = c.bg_highlight })
	set_hl("MiniStatuslineFileinfo", { fg = c.fg, bg = c.bg_highlight })
	set_hl("MiniStatuslineFilename", { fg = c.fg, bg = c.bg_dark })
	set_hl("MiniStatuslineInactive", { fg = c.comment, bg = c.bg_dark })
	set_hl("MiniStatuslineModeCommand", { fg = c.bg, bg = c.sunflower, bold = true })
	set_hl("MiniStatuslineModeInsert", { fg = c.bg, bg = c.bark, bold = true })
	set_hl("MiniStatuslineModeNormal", { fg = c.bg, bg = c.green, bold = true })
	set_hl("MiniStatuslineModeOther", { fg = c.bg, bg = c.mist, bold = true })
	set_hl("MiniStatuslineModeReplace", { fg = c.bg, bg = c.berry, bold = true })
	set_hl("MiniStatuslineModeVisual", { fg = c.bg, bg = c.purple, bold = true })
	-- mini.tabline
	set_hl("MiniTablineCurrent", { fg = c.green_bright, bg = bg, bold = true })
	set_hl("MiniTablineFill", { bg = c.bg_dark })
	set_hl("MiniTablineHidden", { fg = c.comment, bg = c.bg_dark })
	set_hl("MiniTablineModifiedCurrent", { fg = c.orange, bg = bg, bold = true })
	set_hl("MiniTablineModifiedHidden", { fg = c.orange, bg = c.bg_dark })
	set_hl("MiniTablineModifiedVisible", { fg = c.orange, bg = c.bg_dark })
	set_hl("MiniTablineTabpagesection", { fg = c.fg, bg = c.bg_highlight })
	set_hl("MiniTablineVisible", { fg = c.fg, bg = c.bg_dark })
	-- mini.cursorword
	set_hl("MiniCursorword", { bg = c.bg_visual })
	set_hl("MiniCursorwordCurrent", { bg = c.bg_visual })
	-- mini.starter
	set_hl("MiniStarterCurrent", { fg = c.green_bright })
	set_hl("MiniStarterFooter", { fg = c.comment, italic = true })
	set_hl("MiniStarterHeader", { fg = c.green_bright, bold = true })
	set_hl("MiniStarterInactive", { fg = c.comment })
	set_hl("MiniStarterItem", { fg = c.fg })
	set_hl("MiniStarterItemBullet", { fg = c.green })
	set_hl("MiniStarterItemPrefix", { fg = c.sunflower })
	set_hl("MiniStarterSection", { fg = c.green_bright, bold = true })
	set_hl("MiniStarterQuery", { fg = c.sunflower })
	-- mini.surround
	set_hl("MiniSurround", { fg = c.bg, bg = c.sunflower })
	-- mini.jump
	set_hl("MiniJump", { fg = c.bg, bg = c.sunflower })
	set_hl("MiniJump2dSpot", { fg = c.sunflower, bold = true })
	-- mini.files
	set_hl("MiniFilesBorder", { fg = c.border })
	set_hl("MiniFilesBorderModified", { fg = c.orange })
	set_hl("MiniFilesCursorLine", { bg = c.bg_visual })
	set_hl("MiniFilesDirectory", { fg = c.green })
	set_hl("MiniFilesFile", { fg = c.fg })
	set_hl("MiniFilesNormal", { fg = c.fg, bg = c.pmenu })
	set_hl("MiniFilesTitle", { fg = c.green_bright, bold = true })
	set_hl("MiniFilesTitleFocused", { fg = c.green_bright, bg = c.bg_highlight, bold = true })
	-- mini.hipatterns
	set_hl("MiniHipatternsFixme", { fg = c.bg, bg = c.error, bold = true })
	set_hl("MiniHipatternsHack", { fg = c.bg, bg = c.warning, bold = true })
	set_hl("MiniHipatternsNote", { fg = c.bg, bg = c.info, bold = true })
	set_hl("MiniHipatternsTodo", { fg = c.bg, bg = c.hint, bold = true })
	-- mini.pick
	set_hl("MiniPickBorder", { fg = c.border })
	set_hl("MiniPickBorderBusy", { fg = c.sunflower })
	set_hl("MiniPickBorderText", { fg = c.green_bright, bold = true })
	set_hl("MiniPickIconDirectory", { fg = c.green })
	set_hl("MiniPickIconFile", { fg = c.fg })
	set_hl("MiniPickHeader", { fg = c.green_bright, bold = true })
	set_hl("MiniPickMatchCurrent", { bg = c.bg_visual })
	set_hl("MiniPickMatchMarked", { bg = c.selection })
	set_hl("MiniPickMatchRanges", { fg = c.sunflower, bold = true })
	set_hl("MiniPickNormal", { fg = c.fg })
	set_hl("MiniPickPreviewLine", { bg = c.bg_visual })
	set_hl("MiniPickPreviewRegion", { bg = c.selection })
	set_hl("MiniPickPrompt", { fg = c.green_bright })

	-----------------------------------------------------------------------------
	-- Dashboard
	-----------------------------------------------------------------------------
	set_hl("DashboardHeader", { fg = c.green_bright })
	set_hl("DashboardFooter", { fg = c.comment, italic = true })
	set_hl("DashboardCenter", { fg = c.green })
	set_hl("DashboardShortCut", { fg = c.purple })
	set_hl("DashboardKey", { fg = c.sunflower })
	set_hl("DashboardDesc", { fg = c.fg })
	set_hl("DashboardIcon", { fg = c.green_bright })

	-----------------------------------------------------------------------------
	-- Alpha
	-----------------------------------------------------------------------------
	set_hl("AlphaHeader", { fg = c.green_bright })
	set_hl("AlphaFooter", { fg = c.comment, italic = true })
	set_hl("AlphaButtons", { fg = c.green })
	set_hl("AlphaShortcut", { fg = c.sunflower })

	-----------------------------------------------------------------------------
	-- Trouble
	-----------------------------------------------------------------------------
	set_hl("TroubleNormal", { fg = c.fg, bg = c.bg_dark })
	set_hl("TroubleNormalNC", { fg = c.fg, bg = c.bg_dark })
	set_hl("TroubleText", { fg = c.fg })
	set_hl("TroubleCount", { fg = c.purple, bg = c.bg_highlight })
	set_hl("TroubleFile", { fg = c.green })
	set_hl("TroubleFoldIcon", { fg = c.comment })
	set_hl("TroubleLocation", { fg = c.comment })
	set_hl("TroublePreview", { bg = c.bg_visual })
	set_hl("TroubleSource", { fg = c.comment })
	set_hl("TroubleSignError", { fg = c.error })
	set_hl("TroubleSignWarning", { fg = c.warning })
	set_hl("TroubleSignInformation", { fg = c.info })
	set_hl("TroubleSignHint", { fg = c.hint })
	set_hl("TroubleSignOther", { fg = c.purple })
	set_hl("TroubleTextError", { fg = c.error })
	set_hl("TroubleTextWarning", { fg = c.warning })
	set_hl("TroubleTextInformation", { fg = c.info })
	set_hl("TroubleTextHint", { fg = c.hint })
	set_hl("TroubleIndent", { fg = c.border })
	set_hl("TroubleIndentFoldClosed", { fg = c.comment })
	set_hl("TroubleIndentFoldOpen", { fg = c.comment })
	set_hl("TroubleIndentWs", { fg = c.bg_highlight })

	-----------------------------------------------------------------------------
	-- Navic (breadcrumbs)
	-----------------------------------------------------------------------------
	set_hl("NavicText", { fg = c.fg })
	set_hl("NavicSeparator", { fg = c.comment })
	set_hl("NavicIconsFile", { fg = c.fg })
	set_hl("NavicIconsModule", { fg = c.stream })
	set_hl("NavicIconsNamespace", { fg = c.stream })
	set_hl("NavicIconsPackage", { fg = c.stream })
	set_hl("NavicIconsClass", { fg = c.stream })
	set_hl("NavicIconsMethod", { fg = c.green_bright })
	set_hl("NavicIconsProperty", { fg = c.fg })
	set_hl("NavicIconsField", { fg = c.fg })
	set_hl("NavicIconsConstructor", { fg = c.stream })
	set_hl("NavicIconsEnum", { fg = c.stream })
	set_hl("NavicIconsInterface", { fg = c.stream })
	set_hl("NavicIconsFunction", { fg = c.green_bright })
	set_hl("NavicIconsVariable", { fg = c.fg })
	set_hl("NavicIconsConstant", { fg = c.bark })
	set_hl("NavicIconsString", { fg = c.moss })
	set_hl("NavicIconsNumber", { fg = c.sunflower })
	set_hl("NavicIconsBoolean", { fg = c.orange })
	set_hl("NavicIconsArray", { fg = c.stream })
	set_hl("NavicIconsObject", { fg = c.stream })
	set_hl("NavicIconsKey", { fg = c.green })
	set_hl("NavicIconsNull", { fg = c.orange })
	set_hl("NavicIconsEnumMember", { fg = c.bark })
	set_hl("NavicIconsStruct", { fg = c.stream })
	set_hl("NavicIconsEvent", { fg = c.orange })
	set_hl("NavicIconsOperator", { fg = c.fg_dark })
	set_hl("NavicIconsTypeParameter", { fg = c.stream })

	-----------------------------------------------------------------------------
	-- Illuminate
	-----------------------------------------------------------------------------
	set_hl("IlluminatedWordText", { bg = c.bg_visual })
	set_hl("IlluminatedWordRead", { bg = c.bg_visual })
	set_hl("IlluminatedWordWrite", { bg = c.bg_visual })

	-----------------------------------------------------------------------------
	-- Aerial
	-----------------------------------------------------------------------------
	set_hl("AerialNormal", { fg = c.fg, bg = c.bg_dark })
	set_hl("AerialLine", { bg = c.bg_visual })
	set_hl("AerialLineNC", { bg = c.bg_visual })
	set_hl("AerialGuide", { fg = c.border })
	set_hl("AerialBooleanIcon", { fg = c.orange })
	set_hl("AerialClassIcon", { fg = c.stream })
	set_hl("AerialConstantIcon", { fg = c.bark })
	set_hl("AerialConstructorIcon", { fg = c.stream })
	set_hl("AerialEnumIcon", { fg = c.stream })
	set_hl("AerialEnumMemberIcon", { fg = c.bark })
	set_hl("AerialEventIcon", { fg = c.orange })
	set_hl("AerialFieldIcon", { fg = c.fg })
	set_hl("AerialFileIcon", { fg = c.fg })
	set_hl("AerialFunctionIcon", { fg = c.green_bright })
	set_hl("AerialInterfaceIcon", { fg = c.stream })
	set_hl("AerialKeyIcon", { fg = c.green })
	set_hl("AerialMethodIcon", { fg = c.green_bright })
	set_hl("AerialModuleIcon", { fg = c.stream })
	set_hl("AerialNamespaceIcon", { fg = c.stream })
	set_hl("AerialNumberIcon", { fg = c.sunflower })
	set_hl("AerialObjectIcon", { fg = c.stream })
	set_hl("AerialOperatorIcon", { fg = c.fg_dark })
	set_hl("AerialPackageIcon", { fg = c.stream })
	set_hl("AerialPropertyIcon", { fg = c.fg })
	set_hl("AerialStringIcon", { fg = c.moss })
	set_hl("AerialStructIcon", { fg = c.stream })
	set_hl("AerialTypeParameterIcon", { fg = c.stream })
	set_hl("AerialVariableIcon", { fg = c.fg })

	-----------------------------------------------------------------------------
	-- Headlines (markdown headers)
	-----------------------------------------------------------------------------
	set_hl("Headline1", { fg = c.green_bright, bg = c.bg_highlight, bold = true })
	set_hl("Headline2", { fg = c.stream, bg = c.bg_highlight, bold = true })
	set_hl("Headline3", { fg = c.mist, bg = c.bg_highlight, bold = true })
	set_hl("Headline4", { fg = c.purple, bg = c.bg_highlight, bold = true })
	set_hl("Headline5", { fg = c.bark, bg = c.bg_highlight, bold = true })
	set_hl("Headline6", { fg = c.bark, bg = c.bg_highlight, bold = true })
	set_hl("CodeBlock", { bg = c.bg_dark })
	set_hl("Dash", { fg = c.border, bold = true })
	set_hl("Quote", { fg = c.comment, italic = true })

	-----------------------------------------------------------------------------
	-- Neogit
	-----------------------------------------------------------------------------
	set_hl("NeogitBranch", { fg = c.green_bright })
	set_hl("NeogitRemote", { fg = c.purple })
	set_hl("NeogitHunkHeader", { fg = c.fg, bg = c.bg_highlight })
	set_hl("NeogitHunkHeaderHighlight", { fg = c.green_bright, bg = c.bg_visual })
	set_hl("NeogitDiffContext", { fg = c.fg, bg = c.bg_dark })
	set_hl("NeogitDiffContextHighlight", { fg = c.fg, bg = c.bg })
	set_hl("NeogitDiffAdd", { fg = c.git_add, bg = c.diff_add })
	set_hl("NeogitDiffAddHighlight", { fg = c.git_add, bg = c.diff_add })
	set_hl("NeogitDiffDelete", { fg = c.git_delete, bg = c.diff_delete })
	set_hl("NeogitDiffDeleteHighlight", { fg = c.git_delete, bg = c.diff_delete })
	set_hl("NeogitNotificationInfo", { fg = c.info })
	set_hl("NeogitNotificationWarning", { fg = c.warning })
	set_hl("NeogitNotificationError", { fg = c.error })

	-----------------------------------------------------------------------------
	-- nvim-dap (debugging)
	-----------------------------------------------------------------------------
	set_hl("DapBreakpoint", { fg = c.berry })
	set_hl("DapBreakpointCondition", { fg = c.orange })
	set_hl("DapLogPoint", { fg = c.stream })
	set_hl("DapStopped", { fg = c.sunflower })
	set_hl("DapBreakpointRejected", { fg = c.comment })

	set_hl("DapUIScope", { fg = c.green_bright })
	set_hl("DapUIType", { fg = c.stream })
	set_hl("DapUIValue", { fg = c.fg })
	set_hl("DapUIVariable", { fg = c.fg })
	set_hl("DapUIModifiedValue", { fg = c.orange, bold = true })
	set_hl("DapUIDecoration", { fg = c.green_bright })
	set_hl("DapUIThread", { fg = c.green_bright })
	set_hl("DapUIStoppedThread", { fg = c.green_bright })
	set_hl("DapUISource", { fg = c.purple })
	set_hl("DapUILineNumber", { fg = c.green_bright })
	set_hl("DapUIFloatBorder", { fg = c.border })
	set_hl("DapUIWatchesEmpty", { fg = c.error })
	set_hl("DapUIWatchesValue", { fg = c.green_bright })
	set_hl("DapUIWatchesError", { fg = c.error })
	set_hl("DapUIBreakpointsCurrentLine", { fg = c.green_bright, bold = true })
	set_hl("DapUIBreakpointsDisabledLine", { fg = c.comment })
	set_hl("DapUIBreakpointsInfo", { fg = c.info })
	set_hl("DapUIBreakpointsPath", { fg = c.green_bright })
	set_hl("DapUIFrameName", { fg = c.fg })
	set_hl("DapUICurrentFrameName", { fg = c.green_bright, bold = true })
	set_hl("DapUIStepOver", { fg = c.green_bright })
	set_hl("DapUIStepInto", { fg = c.green_bright })
	set_hl("DapUIStepBack", { fg = c.green_bright })
	set_hl("DapUIStepOut", { fg = c.green_bright })
	set_hl("DapUIStop", { fg = c.berry })
	set_hl("DapUIPlayPause", { fg = c.green })
	set_hl("DapUIRestart", { fg = c.green })
	set_hl("DapUIUnavailable", { fg = c.comment })
	set_hl("DapUIWinSelect", { fg = c.green_bright, bold = true })

	-----------------------------------------------------------------------------
	-- nvim-treesitter-context
	-----------------------------------------------------------------------------
	set_hl("TreesitterContext", { bg = c.bg_highlight })
	set_hl("TreesitterContextLineNumber", { fg = c.fg_gutter, bg = c.bg_highlight })
	set_hl("TreesitterContextBottom", { sp = c.border, underline = true })

	-----------------------------------------------------------------------------
	-- Snacks.nvim
	-----------------------------------------------------------------------------
	set_hl("SnacksNormal", { fg = c.fg, bg = c.pmenu })
	set_hl("SnacksDashboardHeader", { fg = c.green_bright })
	set_hl("SnacksDashboardFooter", { fg = c.comment, italic = true })
	set_hl("SnacksDashboardDesc", { fg = c.fg })
	set_hl("SnacksDashboardIcon", { fg = c.green_bright })
	set_hl("SnacksDashboardKey", { fg = c.sunflower })
	set_hl("SnacksDashboardFile", { fg = c.green })
	set_hl("SnacksDashboardDir", { fg = c.comment })
	set_hl("SnacksDashboardSpecial", { fg = c.purple })
	set_hl("SnacksDashboardTitle", { fg = c.green_bright, bold = true })
	set_hl("SnacksNotifierInfo", { fg = c.info })
	set_hl("SnacksNotifierWarn", { fg = c.warning })
	set_hl("SnacksNotifierError", { fg = c.error })
	set_hl("SnacksNotifierDebug", { fg = c.comment })
	set_hl("SnacksNotifierTrace", { fg = c.purple })
	set_hl("SnacksNotifierIconInfo", { fg = c.info })
	set_hl("SnacksNotifierIconWarn", { fg = c.warning })
	set_hl("SnacksNotifierIconError", { fg = c.error })
	set_hl("SnacksNotifierIconDebug", { fg = c.comment })
	set_hl("SnacksNotifierIconTrace", { fg = c.purple })
	set_hl("SnacksNotifierTitleInfo", { fg = c.info })
	set_hl("SnacksNotifierTitleWarn", { fg = c.warning })
	set_hl("SnacksNotifierTitleError", { fg = c.error })
	set_hl("SnacksNotifierTitleDebug", { fg = c.comment })
	set_hl("SnacksNotifierTitleTrace", { fg = c.purple })
	set_hl("SnacksNotifierBorderInfo", { fg = c.info })
	set_hl("SnacksNotifierBorderWarn", { fg = c.warning })
	set_hl("SnacksNotifierBorderError", { fg = c.error })
	set_hl("SnacksNotifierBorderDebug", { fg = c.comment })
	set_hl("SnacksNotifierBorderTrace", { fg = c.purple })
end

return M
